- route:
    id: main
    from:
      uri: platform-http:/camel/chat
      steps:
        - process:
            description: AI message
            ref: createChatMessage
        - to:
            description: call LLM
            uri: langchain4j-chat:getInformation
            parameters:
              chatOperation: CHAT_MULTIPLE_MESSAGES
        - log:
            message: ${body}
- route:
    id: weather tool
    from:
      uri: langchain4j-chat:getInformation?description=get wheather forecast
        of cities around the world&parameter.location=string
      steps:
        - setVariable:
            name: location
            simple:
              expression: "${header.location}"
        - removeHeaders:
            pattern: '*'
        - toD:
            uri: "http://geodb-free-service.wirefreethought.com/v1/geo/places?httpMethod=GET&namePrefix=${variable.location}&limit=1&sort=-population"
        - unmarshal:
            json:
              library: Jackson
        - setVariable:
            name: coordinates
            simple:
              expression: "latitude=${body[data][0][latitude]}&longitude=${body[data][0][longitude]}"
        - removeHeaders:
            pattern: '*'
        - toD:
            uri: "https://api.open-meteo.com/v1/forecast?httpMethod=GET&${variable.coordinates}&current=temperature_2m,precipitation&daily=temperature_2m_max,temperature_2m_min&forecast_days=3"
        - unmarshal:
            json:
              library: Jackson
        - setBody:
            simple:
              expression: >-
                {
                  "unit":"celsius",
                  "temperature": {
                      "today": {
                        "${body[daily][time][0]}": "${body[current][temperature_2m]}"
                      },
                      "forecast": {
                        "${body[daily][time][1]}": {
                          "maximum":"${body[daily][temperature_2m_max][1]}"
                          },
                        "${body[daily][time][2]}": {
                          "maximum":"${body[daily][temperature_2m_max][2]}"
                          }
                      }
                  }
                }
