- route:
    id: main
    from:
      uri: platform-http:/camel/chat
      steps:
        - process:
            description: AI message
            ref: createChatMessage
        - to:
            description: call LLM
            uri: langchain4j-chat:getInformation
            parameters:
              chatOperation: CHAT_MULTIPLE_MESSAGES
        - log:
            message: ${body}
