- route:
    id: main
    from:
      uri: platform-http:/camel/chat
      steps:
        - process:
            description: AI message
            ref: createChatMessage
        - to:
            description: call LLM
            uri: langchain4j-tools:myllm
            parameters:
              tags: all
        - log:
            message: ${body}
- route:
    id: weather tool
    from:
      uri: langchain4j-tools:weather
      parameters:
        tags: all
        description: get wheather forecast of cities around the world
        parameter.location: string
      steps:
        - setVariable:
            name: location
            simple:
              expression: "${header.location}"
        - removeHeaders:
            pattern: '*'
        - toD:
            uri: "http://geodb-free-service.wirefreethought.com/v1/geo/places?httpMethod=GET&namePrefix=${variable.location}&limit=1&sort=-population"
        - unmarshal:
            json:
              library: Jackson
        - setVariable:
            name: coordinates
            simple:
              expression: "latitude=${body[data][0][latitude]}&longitude=${body[data][0][longitude]}"
        - removeHeaders:
            pattern: '*'
        - toD:
            uri: "https://api.open-meteo.com/v1/forecast?httpMethod=GET&${variable.coordinates}&current=temperature_2m,precipitation&daily=temperature_2m_max,temperature_2m_min&forecast_days=3"
        - unmarshal:
            json:
              library: Jackson
        - setBody:
            simple:
              expression: >-
                {
                  "unit":"celsius",
                  "temperature": {
                      "today": {
                        "${body[daily][time][0]}": "${body[current][temperature_2m]}"
                      },
                      "forecast": {
                        "${body[daily][time][1]}": {
                          "maximum":"${body[daily][temperature_2m_max][1]}"
                          },
                        "${body[daily][time][2]}": {
                          "maximum":"${body[daily][temperature_2m_max][2]}"
                          }
                      }
                  }
                }
- route:
    id: tour guide tool
    from:
      uri: langchain4j-tools:tour-guide
      parameters:
        tags: all
        description: get local tour guide contact details in cities around the world
        parameter.location: string
      steps:
        - setProperty:
            name: location
            simple:
              expression: "${header.location}"
        - removeHeaders:
            pattern: '*'
        - log:
            message: "got recomendation request for: ${exchangeProperty.location}"
        - setHeader:
            name: CamelHttpMethod
            simple:
              expression: GET
        - doTry:
            steps:
              - toD:
                  uri: "http://geodb-free-service.wirefreethought.com/v1/geo/places?namePrefix=${exchangeProperty.location}&limit=1&sort=-population"
              - unmarshal:
                  json:
                    library: Jackson
              - setBody:
                  simple:
                    expression: "${body.get(data)[0].get(countryCode)}"
              - log:
                  message: "countryCode is: ${body}"
              - process:
                  ref: getTourGuide
              - log:
                  message: "recommended JSON: ${body}"
              - doCatch:
                  exception:
                    - java.lang.Exception
                  steps:
                    - log:
                        message: "error message was: ${exception.message}"
                    - setBody: 
                        simple: 
                          expression: no hotel recomendation was found.
        - log:
            message: "cc: ${body}"