apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ollama-serve
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ollama-serve
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ollama-serve
    spec:
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: ollama-storage
      containers:
        - name: container
          image: 'quay.io/wcaban/ollama:latest'
          ports:
            - containerPort: 11434
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: ollama-storage
              mountPath: /.ollama
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "ollama pull sam4096/qwen2tools:0.5b"]
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama-serve
  type: ClusterIP