#! /bin/bash
# set -x

CATALOG=https://raw.githubusercontent.com/KaotoIO/catalogs/4.8.0/catalogs/index.json
CWCONFIG=/projects/.code-workspace
LAB=/projects/llm-basics/camel/tools/lab

# Disabled as Kaoto's latest release comes with 4.8.0
# Configure Kaoto's catalogue version
# echo "$(jq '.settings += {"kaoto.catalog.url": "'"$CATALOG"'"}' $CWCONFIG)" > $CWCONFIG

# Point Camel JBang to SNAPSHOT
# grep -rl camel /home/user/.jbang/cache/urls | grep CamelJBang.java | xargs sed -i 's/version:4.*}/version:4.8.0-SNAPSHOT}/g'

# Set Java 17
export JAVA_HOME=$JAVA_HOME_17

# Set Java 17
echo "export JAVA_HOME=\$JAVA_HOME_17" >> ~/.bashrc

if [ ! -d "$LAB" ]; then
  mkdir $LAB
fi

cd $LAB