#! /bin/bash
# set -x

BASE=/projects/llm-basics/camel/tools
LAB=$BASE/lab
FF=$BASE/solution/steps

# Return chapter details when no argument is passed (no chapter requested)
if [ ! "$1" ]; then
  STEP=$(< $BASE/scripts/current)
  echo "Current step: $STEP (Title: `grep '^'$STEP' ' $FF/titles.txt | cut -d' ' -f 2-`)"
  exit
fi

# Get first and last step IDs
cd $FF
FIRST=`ls -d */ | sort -n | cut -f1 -d'/' | head -n 1`
 LAST=`ls -d */ | sort -n | cut -f1 -d'/' | tail -n 1`
cd $OLDPWD

# Abort if chapter requested doesn't exist
if (($1 < $FIRST || $1 > $LAST)); then
  echo ABORTED! no step $1 available.
  exit
fi

NEXT=$1

# to ensure all hidden files & dirs are deleted (.camel) we need to change directory and return
if [ ! -d "$LAB" ]; then
  mkdir $LAB
fi
cd $LAB
ls -A | xargs --no-run-if-empty rm -r
cd $OLDPWD

# Copy chapter sources to lab directory
cp -r $FF/$NEXT/* $LAB
echo "step $1 ready (Title: `grep '^'$1' ' $FF/titles.txt | cut -d' ' -f 2-`)"
echo "$1" > $BASE/scripts/current

